### ISSUE TITLE
[req] add data directory path to config.yaml

### ISSUE THREAD

**Issue by bobpaul** [witchent/matrix-puppet-signal#10]
There is a data directory in the application directory which has several files written to it. By default, this also contains the *.db files. All of the *.db files can be individually controlled by keys in `config.json` but there are several files in `./data/` which have hard coded paths.

I would either like to set the path for the `data` directory or individually set the path for each of these files.

**Comment by witchent** [comment]
As the other request, I think this is a good idea and I regret not doing it earlier. I will try to implement this one as well though it might take longer as more testing will be required (multiple different projects will have to be adapted) (and again I don't have my equipment right now).

**Comment by witchent** [comment]
As the project got superseded I think I won't implement new features. You can have a look at mautrix-signal where you can specify the data directory.
