### ISSUE TITLE
Replies to messages show up in red

### ISSUE THREAD

**Issue by batu-one** [witchent/matrix-puppet-signal#11]
Whenever one of my signal contacts replies to one of my messages, the text shows up in red, including the text of my original message and the whole message is highlighted.

This does not happen when I reply to a message myself.

**Comment by witchent** [comment]
This is a riot-web rendering replies. As I want to support them (so that you can quote other messages) I cannot do anything about it. Maybe you can disable this in the settings of riot.

**Comment by batu-one** [comment]
Ah I see. For anyone looking for more info, this seems to be caused by having the same username and TLD: https://github.com/matrix-org/matrix-doc/issues/2319
