### ISSUE TITLE
New Direct Chats are inserted into Room List

### ISSUE THREAD

**Issue by a22sc** [witchent/matrix-puppet-signal#16]
If a new Direct Chat is Created it's added to the Room List instead of declared as DM.

Since it's not possible anymore to change the room property in Element anymore it would be good to handle this automatically.

**Comment by witchent** [comment]
Sorry about the label, this is not what I wanted to do.
Anyway, I try to declare it as DM in the bridge, but the request gets ignored for some reason. I tried to debug it for a while but did not find the cause.
As a workaround, you can still use Element web/desktop to declare the room as DM.

Also thanks to some Corona related stuff I didn't have any time to work on the bridge for a few weeks now, and this will probably not change in the near future. As I don't think this is a high priority you will probably have to wait until the rewrite for this to be fixed (which again will take a while).

**Comment by jeena** [comment]
Sadly I don't think it's possible in the newest version of Element anymore, for some reason this functionality has been removed.

**Comment by witchent** [comment]
Oh yea, I missed that change, my bad.

**Comment by witchent** [comment]
This is possible via devtools of Element, and as no client wants to support this (everyone's hoping for canonical DMs to arrive at one point) I won't do this here either.
