### ISSUE TITLE
Getting duplicate messages

### ISSUE THREAD

**Issue by batu-one** [witchent/matrix-puppet-signal#7]
I'm receiving duplicate messages from the signal puppet. Found that this has been an issue with the puppet-bridges in general. I tried the proposed solution in this thread: https://github.com/matrix-hacks/matrix-puppet-facebook/issues/6 and set the following in the config:
```
"deduplicationTag" : " \ufeff",
"deduplicationTagPattern" : " \\ufeff$"
```

But the issue persists. I tried another non printable character: '\u200b', but still no luck.

**Comment by witchent** [comment]
That could sadly be a multitude of different problems. Could you maybe answer the following questions?:

1) Are the duplicates messages you received via signal, messages you sent via signal or messages you sent via matrix/riot?
2) When do they duplicate? (For example as soon as you send/receive them, after a few minutes idling, after a bridge restart etc)
3) Did you update the bridge recently? If so, clean install or pull and npm install inside? If not, from when is your install (approximately so I can see which revision you are using).

**Comment by batu-one** [comment]
Yes, thank you!

1. It’s only happening to signal messages I receive in matrix/riot.
2. I receive them after a few minutes idling.
3. Both synapse and the bridge are a fresh install from 3 days ago.

**Comment by witchent** [comment]
Okay this should not be related to the issue you linked above but rather something related to the signal-desktop/client.
Just to be sure, could you check the file:
matrix-puppet-signal/node_modules/signal-client/package.json 
and tell me whats behind the "signal-desktop"? 
If it is not "witchent/Signal-Desktop#dfa935f" I would prefer if you could do a clean install (delete the matrix-puppet-signal folder and clear the npm/yarn cache, e.g. by deleting the.npm/.yarn folders from your homefolder or using npm cache clean, then clone the repo and install, link and configure it again) and report back if it is still doing this.

If it is please send me a log of it happening (node index.js > file.txt until it happens, then clean this file from all personal information and send it e.g. via matrix to @witchent:matrix.org).

**Comment by batu-one** [comment]
Got it, for some reason I had "witchent/Signal-Desktop#f454f5d". How did that happen, bad timing?

I followed your instructions and everything seems to be working as expected now. Thanks a lot for the quick help!

**Comment by witchent** [comment]
Most likely, yes. I forgot some changes when I did the last big update and those seem to have fixed it.

If the problem returns please let me know, for now I will close this issue. And glad I was able to help.
