### ISSUE TITLE
[REQ] Commandline option for path to config.json 

### ISSUE THREAD

**Issue by bobpaul** [witchent/matrix-puppet-signal#8]
I would like to install this to `/usr/lib` such that a single installation can be used by multiple users on the system. For this to work, the install directory must be read-only.

A commandline option, such as ['-c', '--config'] would go a long way towards meeting this goal.
ex:
```node index.js --config /etc/synapse/matrix-puppet-signal/bobpaul-config.yaml```

**Comment by witchent** [comment]
This is a good idea and I will try to implement it. Sadly I don't have access to my test equipment for around two weeks, so I have to postpone all work on the bridge until then. Sorry for the delay.
Of course, pull requests are always welcome.

**Comment by witchent** [comment]
Using a signal bridge with multiple users should now be possible via mautrix-signal.
