### ISSUE TITLE
registration path in config.json is not obeyed

### ISSUE THREAD

**Issue by bobpaul** [witchent/matrix-puppet-signal#9]
config.json contains a key `"registration"` which accepts a file name. It seems this field does not accept a full path.

**Observed Behavior**
- when running `node index.js -r -u .....` the registration file is always placed in the directory with index.js, rather than using the path in config.json
- when running `node index.js` the registration file is searched in the current directory, even if a full path is provided in config.json.

**Expected Behavior**
The path to the registration should always be read from config.json, regardless of what command line parameters are issued.

**Comment by witchent** [comment]
Actually I only pass that argument (through puppet-bridge) to the appservice-bridge (https://github.com/matrix-org/matrix-appservice-bridge) so I would think it is either a configuration issue or an issue with the appservice-bridge.
From a quick glance it should work, but I cannot test it right now (see other issue). Are both "registrationPath" and "registration" set to the same path? Do different names (but same path) work?
